### ISSUE TITLE
create message template for below average (social worse)

### ISSUE THREAD

**Issue by zachll** [Display-Lab/knowledge-base#131]
"Your performance is below average this month"

 - uses the social worse causal pathway with the peer average benchmark

**Comment by mackgalante** [comment]
_Adding relevant links to the existing social worse message templates:_
Vignette - [here](https://github.com/Display-Lab/knowledge-base/tree/main/vignettes/social_worse_vignette#message-templates)
Cedar - [here](https://cedar.metadatacenter.org/instances/edit/https://repo.metadatacenter.org/template-instances/7a786bd2-e0e4-4c13-b3c6-a7228223dd4e?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2Fe07ec526-60ca-486d-b8ae-b1522ae676b8)

**Comment by 00hchung99** [comment]
Social worse has been updated to include the "opportunity_to_improve" message "You may have an opportunity to improve for the measure [Measure name]. Your performance was [recipient performance level as percentage (with numerator and denominator)], below the peer average."

So we can create a message template for this instead of a new message (or perhaps use the original opportunity_to_improve template) This is somewhat in flux as mapping is ongoing.

**Comment by zachll** [comment]
We updated the "opportunity to improve" templates in CEDAR, these are ready to be moved into the knowledge base for testing with social worse and goal worse pathways.

**Comment by zachll** [comment]
We reviewed the status of this issue and the templates in CEDAR, looks like the "Opportunity to Improve Peer Average" message template is ready to be migrated to PFKB in GitHub
