### ISSUE TITLE
implement vignette-base preferences into input messages

### ISSUE THREAD

**Issue by zachll** [Display-Lab/knowledge-base#174]
1. Implement motivating information preference values as it
2. Implement display preferences as 4 variables with a binary preference value for one variable
3. Read display preferences from vignettes readme: https://github.com/Display-Lab/knowledge-base/tree/main/vignettes

**Comment by mackgalante** [comment]
To complete, we need the following information:
1. Key value pairings of the input_message preference model and what causal pathway those values represent
2. Legitimate, non-duplicate data for all causal pathways for each persona (including the goal-based pathways that have been added since the last preference update)
    - Verify data exists and accurately represents all personas
    - Update vignette with corrected data
    - Update input_messages with vignette data

**Comment by 00hchung99** [comment]
Default model in pipeline repo - thinkpudding - input message
Implement preferences into the input message files for the personas

**Comment by 00hchung99** [comment]
All input messages updated in the preference-model-update branch
